# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'First Joint <a href="http://www.gap-system.org/">GAP</a>-&#8203;<a href="http://www.sagemath.org/">Sage</a> Days'
#tagline:          'A GAP school'
description:      'GAP Coding sprint: Jan 13-16, 2016<br> GAP-SageMath Workshop: Jan 18-22, 2016'
location:         '<a href="http://www.st-andrews.ac.uk/">University of St Andrews</a>'
url:              http://gapdays.de
baseurl:          /gap-sage-days2016


exclude: [ "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "program.pdf" ]
